{
 "title": "OpenLDAP Monitoring",
 "tags": [ "ldap" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "DataSource", "query": "prometheus" },
   { "name": "host", "label": "Host", "query": { "query": "label_values(instance)" } },
   { "name": "interval", "label": "Interval", "query": "30s,1m,2m,3m,5m,7m,10m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Confermato che il valore grezzo che esce è in secondi",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openldap_monitored_object{instance=\"$host\",dn=\"cn=Uptime,cn=Time,cn=Monitor\"}",
     "legendFormat": "[{{dn}}] "
    }
   ]
  },
  {
   "title": "CPU Use %",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"$host\"}[$interval]) * 1000",
     "legendFormat": "[{{dn}}] "
    }
   ]
  },
  {
   "title": "LDAP Bind",
   "type": "stat",
   "description": "openldap_bind successful vs unsuccessful ldap bind attempts",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(openldap_bind{result=\"ok\",instance=\"$host\"}[$interval])"
    }
   ]
  },
  {
   "title": "LDAP Dial",
   "type": "stat",
   "description": "openldap_dial successful vs unsuccessful ldap dial attempts",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(openldap_dial{result=\"ok\",instance=\"$host\"}[$interval])"
    }
   ]
  },
  {
   "title": "LDAP Scrape",
   "type": "stat",
   "description": "openldap_scrape successful vs unsuccessful ldap scrape attempts",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(openldap_scrape{result=\"ok\",instance=\"$host\"}[$interval])"
    }
   ]
  },
  {
   "title": "Statistics",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openldap_monitor_counter_object{instance=\"$host\",dn=~\".*cn=Statistics,cn=Monitor\"}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 7, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openldap_monitor_counter_object{instance=\"$host\",dn=~\".*,cn=Connections,cn=Monitor\"}",
     "legendFormat": "{{dn}}"
    }
   ]
  },
  {
   "title": "Waiters",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 7, "x": 13, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openldap_monitor_counter_object{instance=\"$host\",dn=~\".*,cn=Waiters,cn=Monitor\"}",
     "legendFormat": "{{dn}}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openldap_monitored_object{instance=\"$host\",dn=~\".*,cn=Threads,cn=Monitor\"}",
     "legendFormat": "{{dn}}]"
    }
   ]
  },
  {
   "title": "Operations",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 11, "x": 9, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openldap_monitor_operation{dn=~\".*,cn=Operations,cn=Monitor\",instance=\"$host\"}",
     "legendFormat": "{{dn}}]"
    }
   ]
  },
  {
   "title": "Counters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bytes",
     "type": "stat",
     "description": "dn=\"cn=Bytes,cn=Statistics,cn=Monitor\"",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "openldap_monitor_counter_object{instance=\"$host\",dn=\"cn=Bytes,cn=Statistics,cn=Monitor\"}",
       "legendFormat": "[{{dn}}] "
      }
     ]
    },
    {
     "title": "Connessioni Correnti",
     "type": "stat",
     "description": "cn=Current,cn=Connections,cn=Monitor",
     "gridPos": { "h": 4, "w": 2, "x": 2, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "openldap_monitor_counter_object{instance=\"$host\",dn=\"cn=Current,cn=Connections,cn=Monitor\"}",
       "legendFormat": "[{{dn}}] "
      }
     ]
    },
    {
     "title": "Entries",
     "type": "stat",
     "description": "cn=Entries,cn=Statistics,cn=Monitor",
     "gridPos": { "h": 4, "w": 2, "x": 4, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "openldap_monitor_counter_object{instance=\"$host\",dn=\"cn=Entries,cn=Statistics,cn=Monitor\"}",
       "legendFormat": "[{{dn}}] "
      }
     ]
    },
    {
     "title": "Max File Descriptors",
     "type": "stat",
     "description": "cn=Max File Descriptors,cn=Connections,cn=Monitor",
     "gridPos": { "h": 4, "w": 2, "x": 6, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "openldap_monitor_counter_object{instance=\"$host\",dn=\"cn=Max File Descriptors,cn=Connections,cn=Monitor\"}",
       "legendFormat": "[{{dn}}] "
      }
     ]
    },
    {
     "title": "PDUs",
     "type": "stat",
     "description": "cn=PDU,cn=Statistics,cn=Monitor",
     "gridPos": { "h": 4, "w": 2, "x": 8, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "openldap_monitor_counter_object{instance=\"$host\",dn=\"cn=PDU,cn=Statistics,cn=Monitor\"}",
       "legendFormat": "[{{dn}}] "
      }
     ]
    },
    {
     "title": "Waiters Read",
     "type": "stat",
     "description": "cn=Read,cn=Waiters,cn=Monitor",
     "gridPos": { "h": 4, "w": 2, "x": 10, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "openldap_monitor_counter_object{instance=\"$host\",dn=\"cn=Read,cn=Waiters,cn=Monitor\"}",
       "legendFormat": "[{{dn}}] "
      }
     ]
    },
    {
     "title": "Waiters Write",
     "type": "stat",
     "description": "cn=Total,cn=Connections,cn=Monitor",
     "gridPos": { "h": 4, "w": 2, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "openldap_monitor_counter_object{instance=\"$host\",dn=\"cn=Write,cn=Waiters,cn=Monitor\"}",
       "legendFormat": "[{{dn}}] "
      }
     ]
    },
    {
     "title": "Referrals",
     "type": "stat",
     "description": "cn=Referrals,cn=Statistics,cn=Monitor",
     "gridPos": { "h": 4, "w": 2, "x": 14, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "openldap_monitor_counter_object{instance=\"$host\",dn=\"cn=Referrals,cn=Statistics,cn=Monitor\"}",
       "legendFormat": "[{{dn}}] "
      }
     ]
    },
    {
     "title": "Total Connections",
     "type": "stat",
     "description": "cn=Total,cn=Connections,cn=Monitor",
     "gridPos": { "h": 4, "w": 2, "x": 16, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "openldap_monitor_counter_object{instance=\"$host\",dn=\"cn=Total,cn=Connections,cn=Monitor\"}",
       "legendFormat": "[{{dn}}] "
      }
     ]
    }
   ]
  },
  {
   "title": "Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Abandon",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "openldap_monitor_operation{instance=\"$host\",dn=\"cn=Abandon,cn=Operations,cn=Monitor\"}",
       "legendFormat": "[{{dn}}] "
      }
     ]
    },
    {
     "title": "Add",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 2, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "openldap_monitor_operation{dn=\"cn=Add,cn=Operations,cn=Monitor\",instance=\"$host\"}",
       "legendFormat": "[{{dn}}] "
      }
     ]
    },
    {
     "title": "Bind",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 4, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "openldap_monitor_operation{dn=\"cn=Bind,cn=Operations,cn=Monitor\",instance=\"$host\"}",
       "legendFormat": "[{{dn}}] "
      }
     ]
    },
    {
     "title": "Compare",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 6, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "openldap_monitor_operation{dn=\"cn=Compare,cn=Operations,cn=Monitor\",instance=\"$host\"}",
       "legendFormat": "[{{dn}}] "
      }
     ]
    },
    {
     "title": "Delete",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 8, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "openldap_monitor_operation{dn=\"cn=Delete,cn=Operations,cn=Monitor\",instance=\"$host\"}",
       "legendFormat": "[{{dn}}] "
      }
     ]
    },
    {
     "title": "Extended",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 10, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "openldap_monitor_operation{dn=\"cn=Extended,cn=Operations,cn=Monitor\",instance=\"$host\"}",
       "legendFormat": "[{{dn}}] "
      }
     ]
    },
    {
     "title": "Modify",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "openldap_monitor_operation{dn=\"cn=Modify,cn=Operations,cn=Monitor\",instance=\"$host\"}",
       "legendFormat": "[{{dn}}] "
      }
     ]
    },
    {
     "title": "Modrdn",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 14, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "openldap_monitor_operation{dn=\"cn=Modrdn,cn=Operations,cn=Monitor\",instance=\"$host\"}",
       "legendFormat": "[{{dn}}] "
      }
     ]
    },
    {
     "title": "Search",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 16, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "openldap_monitor_operation{dn=\"cn=Search,cn=Operations,cn=Monitor\",instance=\"$host\"}",
       "legendFormat": "[{{dn}}] "
      }
     ]
    },
    {
     "title": "Unbind",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 18, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "openldap_monitor_operation{dn=\"cn=Unbind,cn=Operations,cn=Monitor\",instance=\"$host\"}",
       "legendFormat": "[{{dn}}] "
      }
     ]
    }
   ]
  },
  {
   "title": "Object",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Threads",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "openldap_monitored_object{instance=\"$host\",dn=\"cn=Active,cn=Threads,cn=Monitor\"}",
       "legendFormat": "[{{dn}}] "
      }
     ]
    },
    {
     "title": "Backload Threads",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 2, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "openldap_monitored_object{instance=\"$host\",dn=\"cn=Backload,cn=Threads,cn=Monitor\"}",
       "legendFormat": "[{{dn}}] "
      }
     ]
    },
    {
     "title": "Max Pending Threads",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 4, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "openldap_monitored_object{instance=\"$host\",dn=\"cn=Max Pending,cn=Threads,cn=Monitor\"}",
       "legendFormat": "[{{dn}}] "
      }
     ]
    },
    {
     "title": "Max Threads",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 6, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "openldap_monitored_object{instance=\"$host\",dn=\"cn=Max,cn=Threads,cn=Monitor\"}",
       "legendFormat": "[{{dn}}] "
      }
     ]
    },
    {
     "title": "Open Threads",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 8, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "openldap_monitored_object{instance=\"$host\",dn=\"cn=Open,cn=Threads,cn=Monitor\"}",
       "legendFormat": "[{{dn}}] "
      }
     ]
    },
    {
     "title": "Pending Threads",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 10, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "openldap_monitored_object{instance=\"$host\",dn=\"cn=Pending,cn=Threads,cn=Monitor\"}",
       "legendFormat": "[{{dn}}] "
      }
     ]
    },
    {
     "title": "Starting Threads",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "openldap_monitored_object{instance=\"$host\",dn=\"cn=Starting,cn=Threads,cn=Monitor\"}",
       "legendFormat": "[{{dn}}] "
      }
     ]
    }
   ]
  }
 ]
}